In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/kaggle/input/datathon2025/train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
df.drop(columns=["Id"], inplace=True)
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
for col in df.columns:
    if df[col].isnull().sum() != 0:
        print(col, df[col].isnull().sum(), df[col].dtype)

LotFrontage 259 float64
Alley 1369 object
MasVnrType 872 object
MasVnrArea 8 float64
BsmtQual 37 object
BsmtCond 37 object
BsmtExposure 38 object
BsmtFinType1 37 object
BsmtFinType2 38 object
Electrical 1 object
FireplaceQu 690 object
GarageType 81 object
GarageYrBlt 81 float64
GarageFinish 81 object
GarageQual 81 object
GarageCond 81 object
PoolQC 1453 object
Fence 1179 object
MiscFeature 1406 object

In [5]:
df["Alley"].replace(np.nan,'DoesntExist', inplace=True)

<ipython-input-5-25389c4127d1>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Alley"].replace(np.nan,'DoesntExist', inplace=True)

In [6]:
df["MasVnrType"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-6-bb97f6522662>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["MasVnrType"].replace(np.nan, 'DoesntExist', inplace=True)

In [7]:
df["BsmtQual"].replace(np.nan, 'DoesntExist', inplace=True)
df["BsmtCond"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-7-05a1414d5f5a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BsmtQual"].replace(np.nan, 'DoesntExist', inplace=True)
<ipython-input-7-05a1414d5f5a>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BsmtCond"].replace(np.nan, 'DoesntExist', inplace=True)

In [8]:
df["BsmtFinType2"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-8-3fc52db15a13>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BsmtFinType2"].replace(np.nan, 'DoesntExist', inplace=True)

In [9]:
df["FireplaceQu"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-9-601a473b29ac>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["FireplaceQu"].replace(np.nan, 'DoesntExist', inplace=True)

In [10]:
df["GarageType"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-10-df2e4a11f9ea>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["GarageType"].replace(np.nan, 'DoesntExist', inplace=True)

In [11]:
df["GarageFinish"].replace(np.nan, 'DoesntExist', inplace=True)
df["GarageQual"].replace(np.nan, 'DoesntExist', inplace=True)
df["GarageCond"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-11-b46179d5bd3d>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["GarageFinish"].replace(np.nan, 'DoesntExist', inplace=True)
<ipython-input-11-b46179d5bd3d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["GarageQual"].replace(np.nan, 'DoesntExist', inplace=True)
<ipython-input-11-b46179d5bd3d>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["GarageCond"].replace(np.nan, 'DoesntExist', inplace=True)

In [12]:
df["PoolQC"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-12-ef0b1d74183d>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["PoolQC"].replace(np.nan, 'DoesntExist', inplace=True)

In [13]:
df["Fence"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-13-887759cd3d6b>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Fence"].replace(np.nan, 'DoesntExist', inplace=True)

In [14]:
df["MiscFeature"].replace(np.nan, 'DoesntExist', inplace=True)

<ipython-input-14-7b19cc52b15e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["MiscFeature"].replace(np.nan, 'DoesntExist', inplace=True)

In [15]:
df["AgeWhenSold"] = df["YrSold"] - df["YearBuilt"]
df["RenovatedAgeSold"] = df["YrSold"] - df["YearRemodAdd"]
df.drop(columns=["YrSold", "YearBuilt", "YearRemodAdd"], inplace=True)
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,SaleType,SaleCondition,SalePrice,AgeWhenSold,RenovatedAgeSold
0,60,RL,65.0,8450,Pave,DoesntExist,Reg,Lvl,AllPub,Inside,...,DoesntExist,DoesntExist,DoesntExist,0,2,WD,Normal,208500,5,5
1,20,RL,80.0,9600,Pave,DoesntExist,Reg,Lvl,AllPub,FR2,...,DoesntExist,DoesntExist,DoesntExist,0,5,WD,Normal,181500,31,31
2,60,RL,68.0,11250,Pave,DoesntExist,IR1,Lvl,AllPub,Inside,...,DoesntExist,DoesntExist,DoesntExist,0,9,WD,Normal,223500,7,6
3,70,RL,60.0,9550,Pave,DoesntExist,IR1,Lvl,AllPub,Corner,...,DoesntExist,DoesntExist,DoesntExist,0,2,WD,Abnorml,140000,91,36
4,60,RL,84.0,14260,Pave,DoesntExist,IR1,Lvl,AllPub,FR2,...,DoesntExist,DoesntExist,DoesntExist,0,12,WD,Normal,250000,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,DoesntExist,Reg,Lvl,AllPub,Inside,...,DoesntExist,DoesntExist,DoesntExist,0,8,WD,Normal,175000,8,7
1456,20,RL,85.0,13175,Pave,DoesntExist,Reg,Lvl,AllPub,Inside,...,DoesntExist,MnPrv,DoesntExist,0,2,WD,Normal,210000,32,22
1457,70,RL,66.0,9042,Pave,DoesntExist,Reg,Lvl,AllPub,Inside,...,DoesntExist,GdPrv,Shed,2500,5,WD,Normal,266500,69,4
1458,20,RL,68.0,9717,Pave,DoesntExist,Reg,Lvl,AllPub,Inside,...,DoesntExist,DoesntExist,DoesntExist,0,4,WD,Normal,142125,60,14
1459,20,RL,75.0,9937,Pave,DoesntExist,Reg,Lvl,AllPub,Inside,...,DoesntExist,DoesntExist,DoesntExist,0,6,WD,Normal,147500,43,43

In [27]:
numerical_with_na = ["LotFrontage", "MasVnrArea", "GarageYrBlt"]
categorical_to_numerical = ["Alley", "Street", "MSZoning", "LotShape", "LandContour", "Utilities", "LotConfig", "LandSlope", "Neighborhood", "Condition1", "Condition2", "BldgType", "HouseStyle", "RoofStyle", "RoofMatl", "Exterior1st", "Exterior2nd", "MasVnrType", "ExterQual", "ExterCond", "Foundation", "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinSF1", "BsmtFinType2", "Heating", "HeatingQC", "CentralAir", "Electrical", "KitchenQual", "Functional", "FireplaceQu", "GarageType", "GarageCond", "GarageQual", "GarageFinish", "PavedDrive", "PoolQC", "Fence", "MiscFeature", "SaleType", "SaleCondition"]
normalise = ["LotArea", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "LowQualFinSF", "GrLivArea", "GarageArea", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch", "PoolArea", "MiscVal"]

In [24]:
# print(df.columns)

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF',
       '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'SaleType',
       'SaleCondition', 'SalePrice', 'AgeWhenSold', 'RenovatedAgeSold'],
      dtype='object')

In [25]:
for col in categorical_to_numerical:
    df[col] = df[col].map({k:v for k,v in zip(df[col].sort_values().unique(), [i for i in range(df[col].nunique())])})

In [28]:
for col in normalise:
    df[col] = (df[col] - df[col].mean()) / df[col].std()

In [30]:
for col in df.columns:
    if df[col].isnull().sum() != 0:
        print(col, df[col].isnull().sum(), df[col].dtype)

LotFrontage 259 float64
MasVnrArea 8 float64
BsmtExposure 38 float64
BsmtFinType1 37 float64
Electrical 1 float64
GarageYrBlt 81 float64

In [31]:
df.dropna(inplace=True)

In [32]:
df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,SaleType,SaleCondition,SalePrice,AgeWhenSold,RenovatedAgeSold
0,60,3,65.0,-0.207071,1,0,3,3,0,4,...,0,0,0,-0.087658,2,8,4,208500,5,5
1,20,3,80.0,-0.091855,1,0,3,3,0,2,...,0,0,0,-0.087658,5,8,4,181500,31,31
2,60,3,68.0,0.073455,1,0,0,3,0,4,...,0,0,0,-0.087658,9,8,4,223500,7,6
3,70,3,60.0,-0.096864,1,0,0,3,0,0,...,0,0,0,-0.087658,2,8,0,140000,91,36
4,60,3,84.0,0.375020,1,0,0,3,0,2,...,0,0,0,-0.087658,12,8,4,250000,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,3,62.0,-0.260471,1,0,3,3,0,4,...,0,0,0,-0.087658,8,8,4,175000,8,7
1456,20,3,85.0,0.266316,1,0,3,3,0,4,...,0,3,0,-0.087658,2,8,4,210000,32,22
1457,70,3,66.0,-0.147760,1,0,3,3,0,4,...,0,1,3,4.951415,5,8,4,266500,69,4
1458,20,3,68.0,-0.080133,1,0,3,3,0,4,...,0,0,0,-0.087658,4,8,4,142125,60,14
1459,20,3,75.0,-0.058092,1,0,3,3,0,4,...,0,0,0,-0.087658,6,8,4,147500,43,43

In [33]:
df.to_csv("final_preprocessed_train.csv")